apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
      - mountPath: /data/redis
        name: redis-storage
  volumes:
    - name: redis-storage
      emptyDir: {}
